#!/bin/bash

export NO_ITERATIVE=1

commit() {
    cd "$1" 2>/dev/null || (echo "Dir $1 does not exist" ; return )
    echo "CURRENT PROJECT $(pwd)"
    git-add-commit
}

commitAskingDetails() {
    cd "$1" 2>/dev/null || (echo "Dir $1 does not exist" ; return )
    echo "CURRENT PROJECT $(pwd)"
    commit_change.py full_path

}


commit "$HOME/projects/grimoire"
commit "$HOME/projects/personalscripts"
commit "$HOME/projects/snippet"
commit "$HOME/projects/dotfiles"
commit "$HOME/projects/blog"
commit "$HOME/projects/resume"
commit "$HOME/projects/experiments"
commit "$HOME/Dropbox/projects/vimrc"
commit "$HOME/projects/git_private"
commitAskingDetails "$HOME/projects/PythonSearch"
commit "$HOME/projects/PySearchEntries"
commit "$HOME/projects/machineLearningExperiments"
commit "$HOME/projects/git-assistant"

exit 0
